# Generated by Django 5.2.5 on 2025-08-31 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the candidate.', max_length=200)),
                ('photo_url', models.URLField(help_text="A direct URL to the candidate's formal picture.", max_length=500)),
                ('forum', models.CharField(help_text='The forum or party the candidate represents.', max_length=200)),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='The current number of votes received.')),
            ],
            options={
                'ordering': ['-vote_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='The unique student ID number.', max_length=50, unique=True)),
                ('has_voted', models.BooleanField(default=False, help_text='True if the student has already cast their votes.')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.candidate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'candidate')},
            },
        ),
    ]
