# Generated by Django 5.2.5 on 2025-09-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_university(apps, schema_editor):
    """Creates a placeholder university so existing candidates have something to point to."""
    University = apps.get_model('core', 'University')
    University.objects.get_or_create(
        id=1,
        defaults={
            'name': 'Default University',
            'university_id': 'DEFAULT',
            'location': '',
        }
    )

def noop(apps, schema_editor):
    """Reverse migration: nothing to undo for data creation."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create the University table first
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('university_id', models.CharField(help_text='A unique ID for the university, e.g., MSRIT_BLR', max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),

        # 2. Seed the default university BEFORE any FK columns are added
        migrations.RunPython(create_default_university, noop),

        # 3. Alter existing fields
        migrations.AlterField(
            model_name='candidate',
            name='forum',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='core.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='core.student'),
        ),

        # 4. Create Profile (depends on University already existing)
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
        ),

        # 5. Add FK columns — safe now because University id=1 exists
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.university'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.university'),
            preserve_default=False,
        ),

        # 6. Apply unique constraint
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('university', 'student_id')},
        ),
    ]