# Generated by Django 5.1.1 on 2026-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_alter_candidate_forum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='nota_votes',
            field=models.PositiveIntegerField(default=0, help_text='Total NOTA votes accumulated, including unused votes from partial ballots.'),
        ),
    ]
