# Generated by Django 5.1.1 on 2026-08-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_university_nota_votes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('university', 'forum')},
        ),
    ]
