# Generated by Django 5.1.1 on 2026-08-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='nota_votes',
        ),
    ]
