# Generated by Django 5.1.1 on 2026-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_university_nota_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.ImageField(max_length=500, upload_to='candidates/'),
        ),
    ]
